# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-cloudpartnerhub-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Frontend Dependencies
        working-directory: 'Projeto Cloud Partner Hub'
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps

      - name: Build Frontend
        working-directory: 'Projeto Cloud Partner Hub'
        run: |
          npx vite build

      - name: Prepare Deployment Package
        working-directory: 'Projeto Cloud Partner Hub'
        run: |
          mkdir -p server/public
          cp -r dist/* server/public/

      - name: Install Server Dependencies
        working-directory: 'Projeto Cloud Partner Hub/server'
        run: |
          rm -rf node_modules package-lock.json
          npm install --production --legacy-peer-deps

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: 'Projeto Cloud Partner Hub/server'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BEA2A2E72C0D48AFB9A8B9EE42FEFAB5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_80FADE31FFFA44709463E17517D9C3F1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D702E5FB68074DD69496F47397FA17E1 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-cloudpartnerhub-frontend'
          slot-name: 'Production'
          package: .
          